#!/bin/bash
# =============================================================================
# Schema Crawler — Generates org schema docs for the RAG knowledge base
# 
# Usage:
#   schema-crawler.sh [--org dev] [--output file|rag|both] [--objects all|custom|list]
#   schema-crawler.sh --org prod --output both
#   schema-crawler.sh --org dev --objects "Case,Account,Contact"
#
# Outputs structured markdown files describing the Salesforce org schema:
#   - Objects, fields, relationships, record types
#   - Validation rules, triggers, flows
#   - Permission sets, profiles
#
# Can write to knowledge/ files, push to RAG API, or both.
# =============================================================================

set -euo pipefail

# Defaults
ORG="dev"
OUTPUT="both"
OBJECTS="custom"
ENHANCE="false"
KNOWLEDGE_DIR="/home/node/.openclaw/workspace/knowledge/salesforce"
RAG_URL="http://127.0.0.1:${RAG_PORT:-8081}"
INCLUDE_STANDARD="Account,Contact,Case,Opportunity,Lead,Campaign,Task,Event,User"
ENHANCE_SCRIPT="/opt/rag/enhance.py"

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --org) ORG="$2"; shift 2 ;;
    --output) OUTPUT="$2"; shift 2 ;;
    --objects) OBJECTS="$2"; shift 2 ;;
    --knowledge-dir) KNOWLEDGE_DIR="$2"; shift 2 ;;
    --enhance) ENHANCE="true"; shift ;;
    --help) echo "Usage: schema-crawler.sh [--org dev] [--output file|rag|both] [--objects all|custom|\"Obj1,Obj2\"] [--enhance]"; exit 0 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

ENHANCE_LABEL=""
if [[ "$ENHANCE" == "true" ]]; then
  ENHANCE_LABEL=" | LLM: Gemini Flash"
fi
echo "🔍 Schema Crawler — Org: $ORG | Output: $OUTPUT | Objects: $OBJECTS$ENHANCE_LABEL"
echo "=================================================="

mkdir -p "$KNOWLEDGE_DIR/schema"

# ---------------------------------------------------------------------------
# Helper: Query SF and return JSON
# ---------------------------------------------------------------------------
sf_query() {
  local query="$1"
  sf data query --query "$query" --target-org "$ORG" --json 2>/dev/null | jq -r '.result.records // []'
}

# ---------------------------------------------------------------------------
# Helper: Write markdown to file and/or RAG
# ---------------------------------------------------------------------------
write_output() {
  local filename="$1"
  local title="$2"
  local category="$3"
  local content="$4"

  if [[ "$OUTPUT" == "file" || "$OUTPUT" == "both" ]]; then
    echo "$content" > "$KNOWLEDGE_DIR/schema/$filename"
    echo "  📄 Wrote $filename"
  fi

  if [[ "$OUTPUT" == "rag" || "$OUTPUT" == "both" ]]; then
    local json_content
    json_content=$(echo "$content" | jq -Rs .)
    curl -s -X POST "$RAG_URL/rag/documents" \
      -H "Content-Type: application/json" \
      -d "{\"title\": \"$title\", \"content\": $json_content, \"category\": \"$category\", \"source_id\": \"schema/$filename\"}" \
      > /dev/null 2>&1 && echo "  🧠 Pushed to RAG: $title" || echo "  ⚠️ RAG push failed for $title"
  fi
}

# ---------------------------------------------------------------------------
# Step 1: Discover objects
# ---------------------------------------------------------------------------
echo ""
echo "📦 Step 1: Discovering objects..."

# Get custom objects
CUSTOM_OBJECTS=$(sf_query "SELECT QualifiedApiName, Label, Description FROM EntityDefinition WHERE IsCustomizable = true AND IsCustomSetting = false AND QualifiedApiName LIKE '%__c' ORDER BY Label" | jq -r '.[].QualifiedApiName' 2>/dev/null || echo "")

if [[ "$OBJECTS" == "all" ]]; then
  OBJECT_LIST="$INCLUDE_STANDARD"
  if [[ -n "$CUSTOM_OBJECTS" ]]; then
    OBJECT_LIST="$OBJECT_LIST,$(echo "$CUSTOM_OBJECTS" | tr '\n' ',' | sed 's/,$//')"
  fi
elif [[ "$OBJECTS" == "custom" ]]; then
  # Custom objects + key standard objects
  OBJECT_LIST="$INCLUDE_STANDARD"
  if [[ -n "$CUSTOM_OBJECTS" ]]; then
    OBJECT_LIST="$OBJECT_LIST,$(echo "$CUSTOM_OBJECTS" | tr '\n' ',' | sed 's/,$//')"
  fi
else
  # Specific objects provided
  OBJECT_LIST="$OBJECTS"
fi

echo "  Found objects: $(echo "$OBJECT_LIST" | tr ',' '\n' | wc -l | tr -d ' ') total"

# ---------------------------------------------------------------------------
# Step 2: Generate object inventory
# ---------------------------------------------------------------------------
echo ""
echo "📋 Step 2: Generating object inventory..."

INVENTORY="# Salesforce Object Inventory — $ORG org\n\n"
INVENTORY+="*Auto-generated by Schema Crawler on $(date -u '+%Y-%m-%d %H:%M UTC')*\n\n"
INVENTORY+="## Custom Objects\n\n"

if [[ -n "$CUSTOM_OBJECTS" ]]; then
  while IFS= read -r obj; do
    [[ -z "$obj" ]] && continue
    LABEL=$(sf_query "SELECT Label FROM EntityDefinition WHERE QualifiedApiName = '$obj'" | jq -r '.[0].Label // "unknown"' 2>/dev/null || echo "$obj")
    INVENTORY+="- **$obj** — $LABEL\n"
  done <<< "$CUSTOM_OBJECTS"
else
  INVENTORY+="*(No custom objects found)*\n"
fi

INVENTORY+="\n## Key Standard Objects\n\n"
IFS=',' read -ra STD_OBJS <<< "$INCLUDE_STANDARD"
for obj in "${STD_OBJS[@]}"; do
  INVENTORY+="- **$obj**\n"
done

if [[ "$ENHANCE" == "true" ]]; then
  echo -e "$INVENTORY" > /tmp/raw-inventory.md
  python3 "$ENHANCE_SCRIPT" --type inventory --org "$ORG" --input /tmp/raw-inventory.md --output /tmp/enhanced-inventory.md 2>&1
  if [[ -f /tmp/enhanced-inventory.md ]]; then
    INVENTORY=$(cat /tmp/enhanced-inventory.md)
    rm -f /tmp/raw-inventory.md /tmp/enhanced-inventory.md
  fi
fi

write_output "object-inventory.md" "Salesforce Object Inventory ($ORG)" "salesforce" "$(echo -e "$INVENTORY")"

# ---------------------------------------------------------------------------
# Step 3: Generate per-object schema docs
# ---------------------------------------------------------------------------
echo ""
echo "🔧 Step 3: Generating per-object schema docs..."

IFS=',' read -ra ALL_OBJECTS <<< "$OBJECT_LIST"
for OBJ_API in "${ALL_OBJECTS[@]}"; do
  OBJ_API=$(echo "$OBJ_API" | xargs)  # trim whitespace
  [[ -z "$OBJ_API" ]] && continue

  echo "  Processing: $OBJ_API..."

  # Get object label
  OBJ_LABEL=$(sf_query "SELECT Label FROM EntityDefinition WHERE QualifiedApiName = '$OBJ_API'" | jq -r '.[0].Label // "unknown"' 2>/dev/null || echo "$OBJ_API")

  DOC="# $OBJ_LABEL ($OBJ_API)\n\n"
  DOC+="*Auto-generated by Schema Crawler on $(date -u '+%Y-%m-%d %H:%M UTC')*\n\n"

  # Fields
  DOC+="## Fields\n\n"
  DOC+="| API Name | Label | Type | Required | Description |\n"
  DOC+="|----------|-------|------|----------|-------------|\n"

  FIELDS=$(sf_query "SELECT QualifiedApiName, Label, DataType, IsRequired, Description FROM FieldDefinition WHERE EntityDefinition.QualifiedApiName = '$OBJ_API' ORDER BY QualifiedApiName" 2>/dev/null || echo "[]")

  if [[ "$FIELDS" != "[]" && -n "$FIELDS" ]]; then
    echo "$FIELDS" | jq -r '.[] | "| \(.QualifiedApiName // "-") | \(.Label // "-") | \(.DataType // "-") | \(.IsRequired // false) | \(.Description // "-") |"' 2>/dev/null >> /tmp/fields_tmp.md || true
    if [[ -f /tmp/fields_tmp.md ]]; then
      DOC+="$(cat /tmp/fields_tmp.md)\n"
      rm -f /tmp/fields_tmp.md
    fi
  else
    DOC+="| *(unable to retrieve fields)* | | | | |\n"
  fi

  # Record Types
  DOC+="\n## Record Types\n\n"
  RECORD_TYPES=$(sf_query "SELECT DeveloperName, Name, Description, IsActive FROM RecordType WHERE SObjectType = '$OBJ_API' ORDER BY Name" 2>/dev/null || echo "[]")

  if [[ "$RECORD_TYPES" != "[]" && -n "$RECORD_TYPES" ]]; then
    RT_COUNT=$(echo "$RECORD_TYPES" | jq 'length' 2>/dev/null | tr -d '[:space:]' || echo "0")
    if [[ "$RT_COUNT" =~ ^[0-9]+$ ]] && [[ "$RT_COUNT" -gt 0 ]]; then
      DOC+="| Developer Name | Label | Active | Description |\n"
      DOC+="|---------------|-------|--------|-------------|\n"
      echo "$RECORD_TYPES" | jq -r '.[] | "| \(.DeveloperName // "-") | \(.Name // "-") | \(.IsActive // "-") | \(.Description // "-") |"' 2>/dev/null >> /tmp/rt_tmp.md || true
      if [[ -f /tmp/rt_tmp.md ]]; then
        DOC+="$(cat /tmp/rt_tmp.md)\n"
        rm -f /tmp/rt_tmp.md
      fi
    else
      DOC+="*(No record types)*\n"
    fi
  else
    DOC+="*(No record types)*\n"
  fi

  # Validation Rules (only for custom objects — standard object VRs need Metadata API)
  if [[ "$OBJ_API" == *"__c" ]]; then
    DOC+="\n## Validation Rules\n\n"
    VR=$(sf_query "SELECT ValidationName, Active, Description, ErrorMessage FROM ValidationRule WHERE EntityDefinition.QualifiedApiName = '$OBJ_API'" 2>/dev/null || echo "[]")
    if [[ "$VR" != "[]" && -n "$VR" ]]; then
      VR_COUNT=$(echo "$VR" | jq 'length' 2>/dev/null | tr -d '[:space:]' || echo "0")
      if [[ "$VR_COUNT" =~ ^[0-9]+$ ]] && [[ "$VR_COUNT" -gt 0 ]]; then
        DOC+="| Name | Active | Description | Error Message |\n"
        DOC+="|------|--------|-------------|---------------|\n"
        echo "$VR" | jq -r '.[] | "| \(.ValidationName // "-") | \(.Active // "-") | \(.Description // "-") | \(.ErrorMessage // "-") |"' 2>/dev/null >> /tmp/vr_tmp.md || true
        if [[ -f /tmp/vr_tmp.md ]]; then
          DOC+="$(cat /tmp/vr_tmp.md)\n"
          rm -f /tmp/vr_tmp.md
        fi
      else
        DOC+="*(No validation rules)*\n"
      fi
    else
      DOC+="*(No validation rules)*\n"
    fi
  fi

  # Slugify object name for filename
  FILENAME="schema-$(echo "$OBJ_API" | tr '[:upper:]' '[:lower:]' | sed 's/__c$//' | sed 's/_/-/g').md"

  # LLM Enhancement
  if [[ "$ENHANCE" == "true" ]]; then
    echo -e "$DOC" > /tmp/raw-schema.md
    python3 "$ENHANCE_SCRIPT" --type object --name "$OBJ_API" --org "$ORG" --input /tmp/raw-schema.md --output /tmp/enhanced-schema.md 2>&1
    if [[ -f /tmp/enhanced-schema.md ]]; then
      DOC=$(cat /tmp/enhanced-schema.md)
      rm -f /tmp/raw-schema.md /tmp/enhanced-schema.md
    fi
  fi

  write_output "$FILENAME" "$OBJ_LABEL Schema ($OBJ_API)" "salesforce" "$(echo -e "$DOC")"
done

# ---------------------------------------------------------------------------
# Step 4: Permission Sets
# ---------------------------------------------------------------------------
echo ""
echo "🔐 Step 4: Generating permission set inventory..."

PERMS="# Permission Sets — $ORG org\n\n"
PERMS+="*Auto-generated by Schema Crawler on $(date -u '+%Y-%m-%d %H:%M UTC')*\n\n"

PS_DATA=$(sf_query "SELECT Name, Label, Description FROM PermissionSet WHERE IsCustom = true ORDER BY Label" 2>/dev/null || echo "[]")
if [[ "$PS_DATA" != "[]" && -n "$PS_DATA" ]]; then
  PERMS+="| API Name | Label | Description |\n"
  PERMS+="|----------|-------|-------------|\n"
  echo "$PS_DATA" | jq -r '.[] | "| \(.Name // "-") | \(.Label // "-") | \(.Description // "-") |"' 2>/dev/null >> /tmp/ps_tmp.md || true
  if [[ -f /tmp/ps_tmp.md ]]; then
    PERMS+="$(cat /tmp/ps_tmp.md)\n"
    rm -f /tmp/ps_tmp.md
  fi
else
  PERMS+="*(No custom permission sets found)*\n"
fi

if [[ "$ENHANCE" == "true" ]]; then
  echo -e "$PERMS" > /tmp/raw-perms.md
  python3 "$ENHANCE_SCRIPT" --type permissions --org "$ORG" --input /tmp/raw-perms.md --output /tmp/enhanced-perms.md 2>&1
  if [[ -f /tmp/enhanced-perms.md ]]; then
    PERMS=$(cat /tmp/enhanced-perms.md)
    rm -f /tmp/raw-perms.md /tmp/enhanced-perms.md
  fi
fi

write_output "permission-sets.md" "Permission Sets ($ORG)" "salesforce" "$(echo -e "$PERMS")"

# ---------------------------------------------------------------------------
# Step 5: Profiles
# ---------------------------------------------------------------------------
echo ""
echo "👤 Step 5: Generating profile inventory..."

PROFILES="# Profiles — $ORG org\n\n"
PROFILES+="*Auto-generated by Schema Crawler on $(date -u '+%Y-%m-%d %H:%M UTC')*\n\n"

PROF_DATA=$(sf_query "SELECT Name FROM Profile ORDER BY Name" 2>/dev/null || echo "[]")
if [[ "$PROF_DATA" != "[]" && -n "$PROF_DATA" ]]; then
  PROFILES+="| Profile Name |\n"
  PROFILES+="|-------------|\n"
  echo "$PROF_DATA" | jq -r '.[] | "| \(.Name // "-") |"' 2>/dev/null >> /tmp/prof_tmp.md || true
  if [[ -f /tmp/prof_tmp.md ]]; then
    PROFILES+="$(cat /tmp/prof_tmp.md)\n"
    rm -f /tmp/prof_tmp.md
  fi
else
  PROFILES+="*(Unable to retrieve profiles)*\n"
fi

write_output "profiles.md" "Profiles ($ORG)" "salesforce" "$(echo -e "$PROFILES")"

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo ""
echo "=================================================="
echo "✅ Schema crawl complete!"
echo "  Output: $OUTPUT"
echo "  Knowledge dir: $KNOWLEDGE_DIR/schema/"
echo ""
echo "To trigger a RAG re-sync of file-based docs:"
echo "  curl -X POST $RAG_URL/rag/sync -H 'Content-Type: application/json' -d '{\"force\": false}'"
